# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration', '0001_initial'),
        ('book_reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.CharField(max_length=500)),
                ('rating', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_reviews.Book')),
                ('review_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_and_registration.User')),
            ],
        ),
    ]
