# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_book', to='book_reviews.Book'),
        ),
    ]
